### ISSUE TITLE
Bug : Silent exception in MediaCodec when unsupported resolution is used.  

### ISSUE THREAD

**Issue by jd-alexander** [Automattic/stories-android#333]
## Expected behavior
The app should propagate the exception up to the user in a user-friendly manner and log it so it can be resolved. 

## Actual behavior
Android's media codec logs the exception and the UI doesn't respond to the fatal operation that occurred. 

## Exception details 
> 2020-05-06 21:30:48.874 10948-29022/com.automattic.portkey E/ACodec: [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010

 https://stackoverflow.com/questions/36915383/what-does-error-code-1010-in-android-mediacodec-mean

### Steps to reproduce the behavior
1. For me, I created a new hardware profile in the AVD manager with a resolution of `1096 x 1920`
2. I created a new story and captured video. 
3. I pressed Publish so the save operation could be done. 
4. The operation fails and we are still on the compose screen and the log is made. 

Tested on Google Pixel 3a XL, Android 10, https://github.com/Automattic/portkey-android/pull/329 ()

**Comment by mzorz** [comment]
I was able to see the exception logged, this was actually while playing the recorded video but not when saving the new video with mp4composer.

Did step by step debugging on a new AVD with he specified scree size (1096x1920) and observed `[normalizeTargetVideoSize()](https://github.com/Automattic/stories-android/blob/46b22f9c1db750a6b6a28eff0727047ac6359df0/photoeditor/src/main/java/com/automattic/photoeditor/PhotoEditor.kt#L866-L912 )`  gets called correctly, and it ends up not normalizing it which is OK as per the algorithm. In the end the video got saved properly and [published to the site](https://mzorz.files.wordpress.com/2020/08/wp-1597938449028.mp4), so WFM I guess. Closing for now, as many other improvements have been made since then 👍 (will re open if needed ofc)
